In [1]:
from keras.models import Sequential
from keras.layers import*
import numpy as np
X=np.array([1,4,7,10,13,16,19,22,25,28,31,34,37,40,43])
X.shape

(15,)

In [2]:
y=np.array([[2,3],[5,6],[8,9],[11,12],[14,15],[17,18],[20,21],[23,24],[26,27],[29,30],[32,33],[35,36],[38,39],[41,42],[44,45]])

In [3]:
y.shape

(15, 2)

In [4]:
X[4]

13

In [5]:
y[4]

array([14, 15])

In [6]:
n_time_step = 1 
n_feature =1 

In [14]:
X=X.reshape((15,n_time_step,n_feature ))
X.shape

(15, 1, 1)

In [8]:
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_time_step, n_feature)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
model.fit(X, y, epochs=1000, validation_split=0.2, batch_size=3)

Epoch 1/1000
4/4 [==============================] - 2s 170ms/step - loss: 461.7343 - accuracy: 0.0000e+00 - val_loss: 1710.3746 - val_accuracy: 0.0000e+00
Epoch 2/1000
4/4 [==============================] - 0s 11ms/step - loss: 458.9402 - accuracy: 0.0000e+00 - val_loss: 1700.6958 - val_accuracy: 0.0000e+00
Epoch 3/1000
4/4 [==============================] - 0s 13ms/step - loss: 455.7802 - accuracy: 0.0000e+00 - val_loss: 1690.5306 - val_accuracy: 0.0000e+00
Epoch 4/1000
4/4 [==============================] - 0s 12ms/step - loss: 452.0769 - accuracy: 0.0000e+00 - val_loss: 1679.9762 - val_accuracy: 0.0000e+00
Epoch 5/1000
4/4 [==============================] - 0s 12ms/step - loss: 448.4518 - accuracy: 0.0000e+00 - val_loss: 1668.5023 - val_accuracy: 0.0000e+00
Epoch 6/1000
4/4 [==============================] - 0s 12ms/step - loss: 444.3019 - accuracy: 0.0000e+00 - val_loss: 1655.8251 - val_accuracy: 0.0000e+00
Epoch 7/1000
4/4 [==============================] - 0s 11ms/step - loss: 43

In [9]:
y_pred=model.predict(X)
y_pred

1/1 [==============================] - 0s 303ms/step


array([[ 2.1228874,  2.6739664],
       [ 5.0223145,  5.863291 ],
       [ 8.043555 ,  9.056142 ],
       [11.022934 , 12.115462 ],
       [13.975115 , 15.086007 ],
       [16.93532  , 18.030828 ],
       [19.921103 , 20.987188 ],
       [22.933016 , 23.96678  ],
       [25.962988 , 26.966772 ],
       [29.000683 , 29.978891 ],
       [32.036667 , 32.994354 ],
       [35.063457 , 36.005825 ],
       [38.07556  , 39.007877 ],
       [41.06915  , 41.99674  ],
       [44.04167  , 44.969936 ]], dtype=float32)

In [10]:
model.evaluate(X,y)

1/1 [==============================] - 0s 332ms/step - loss: 0.0069 - accuracy: 1.0000


[0.00687280623242259, 1.0]

In [16]:
model.predict([[[10]]])

1/1 [==============================] - 0s 68ms/step


array([[11.022933, 12.115461]], dtype=float32)

In [17]:
model.predict([[[11]]])

1/1 [==============================] - 0s 33ms/step


array([[12.008051, 13.112047]], dtype=float32)

In [18]:
model.predict([[[7]]])

1/1 [==============================] - 0s 34ms/step


array([[8.043554, 9.056143]], dtype=float32)