In [13]:
!wget http://cb.lk/covid_19  


--2023-03-04 08:54:01--  http://cb.lk/covid_19
Resolving cb.lk (cb.lk)... 104.21.72.203, 172.67.187.81, 2606:4700:3032::ac43:bb51, ...
Connecting to cb.lk (cb.lk)|104.21.72.203|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/s/7rjw6oet4za01op/CovidDataset-20200427T133042Z-001.zip?dl=0 [following]
--2023-03-04 08:54:02--  https://www.dropbox.com/s/7rjw6oet4za01op/CovidDataset-20200427T133042Z-001.zip?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.80.18, 2620:100:6030:18::a27d:5012
Connecting to www.dropbox.com (www.dropbox.com)|162.125.80.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/7rjw6oet4za01op/CovidDataset-20200427T133042Z-001.zip [following]
--2023-03-04 08:54:03--  https://www.dropbox.com/s/raw/7rjw6oet4za01op/CovidDataset-20200427T133042Z-001.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc0f8

In [14]:
!unzip covid_19

Archive:  covid_19
replace CovidDataset/Val/Covid/88de9d8c39e946abd495b37cd07d89e5-6531-0.jpg? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

In [15]:
import tensorflow as tf
from tensorflow import keras
from keras.models import * 
from keras.layers import *

In [16]:
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255,)
test_datagen = ImageDataGenerator(rescale=1./255)

train_set = train_datagen.flow_from_directory(
        '/content/CovidDataset/Train/',
        target_size=(224, 224),batch_size=32,class_mode='binary',
        shuffle=True)
       

test_set = test_datagen.flow_from_directory(
        '/content/CovidDataset/Val/',
        target_size=(224, 224),batch_size=32,class_mode='binary',
        shuffle=True)

Found 224 images belonging to 2 classes.
Found 60 images belonging to 2 classes.


In [17]:
test_set.labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [18]:
test_set.filenames

['Covid/16654_1_1.png',
 'Covid/16654_2_1.jpg',
 'Covid/16654_4_1.jpg',
 'Covid/23E99E2E-447C-46E5-8EB2-D35D12473C39.png',
 'Covid/31BA3780-2323-493F-8AED-62081B9C383B.jpeg',
 'Covid/353889E0-A1E8-4F9E-A0B8-F24F36BCFBFB.jpeg',
 'Covid/4-x-day1.jpg',
 'Covid/41591_2020_819_Fig1_HTML.webp-day10.png',
 'Covid/41591_2020_819_Fig1_HTML.webp-day5.png',
 'Covid/4e43e48d52c9e2d4c6c1fb9bc1544f_jumbo.jpeg',
 'Covid/53EC07C9-5CC6-4BE4-9B6F-D7B0D72AAA7E.jpeg',
 'Covid/58cb9263f16e94305c730685358e4e_jumbo.jpeg',
 'Covid/6C94A287-C059-46A0-8600-AFB95F4727B7.jpeg',
 'Covid/6CB4EFC6-68FA-4CD5-940C-BEFA8DAFE9A7.jpeg',
 'Covid/6b3bdbc31f65230b8cdcc3cef5f8ba8a-40ac-0.jpg',
 'Covid/6b44464d-73a7-4cf3-bbb6-ffe7168300e3.annot.original.jpeg',
 'Covid/7AF6C1AF-D249-4BD2-8C26-449304105D03.jpeg',
 'Covid/7C69C012-7479-493F-8722-ABC29C60A2DD.jpeg',
 'Covid/85E52EB3-56E9-4D67-82DA-DEA247C82886.jpeg',
 'Covid/88de9d8c39e946abd495b37cd07d89e5-2ee6-0.jpg',
 'Covid/88de9d8c39e946abd495b37cd07d89e5-6531-0.jpg',
 'Covi

In [19]:
import os
os.listdir('/content/CovidDataset')

['Train', 'Val']

In [20]:
len(test_set)

2

In [21]:
test_set.batch_size

32

In [22]:
train_set.batch_size

32

In [23]:
import numpy as np

In [24]:
test_set1=test_set[0][1]
test_set2=test_set[1][1]
test_set_labels=np.append(test_set1,test_set2)
# test_set_labels=np.concatenate((test_set1,test_set2),axis = 0)
test_set_labels

array([0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 1., 1.], dtype=float32)

In [25]:
model=Sequential()
model.add(Conv2D(96, kernel_size=(11, 11), strides=(4,4), padding="same", activation='relu', input_shape=(224,224,3)))
model.add(MaxPooling2D(pool_size=(3, 3),strides=(2,2))) 
model.add(Conv2D(256, (5, 5),strides=(1,1),padding="same", activation='relu'))
model.add(MaxPooling2D(pool_size=(3, 3),strides=(2,2)))
model.add(Conv2D(384, (3, 3),strides=(1,1), padding="same", activation='relu'))
model.add(Conv2D(384, (3, 3),strides=(1,1), padding="same", activation='relu'))
model.add(Conv2D(384, (3, 3),strides=(1,1), padding="same", activation='relu'))
model.add(MaxPooling2D(pool_size=(3, 3),strides=(2,2),padding="same")) 
model.add(Flatten()) 
model.add(Dense(4096, activation='relu')) 
model.add(Dense(4096, activation='relu')) 
model.add(Dense(1, activation='sigmoid'))

In [26]:
model.compile(loss=keras.losses.binary_crossentropy, optimizer="sgd", metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 56, 56, 96)        34944     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 27, 27, 96)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 27, 27, 256)       614656    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 13, 13, 256)      0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 13, 13, 384)       885120    
                                                                 
 conv2d_3 (Conv2D)           (None, 13, 13, 384)       1

In [27]:
model.fit( train_set, epochs=10,validation_data=test_set,steps_per_epoch=len(train_set),validation_steps=len(test_set))

Epoch 1/10
7/7 [==============================] - 19s 1s/step - loss: 0.6920 - accuracy: 0.4643 - val_loss: 0.6889 - val_accuracy: 0.5000
Epoch 2/10
7/7 [==============================] - 8s 1s/step - loss: 0.6873 - accuracy: 0.5000 - val_loss: 0.6851 - val_accuracy: 0.6667
Epoch 3/10
7/7 [==============================] - 8s 1s/step - loss: 0.6846 - accuracy: 0.6339 - val_loss: 0.6810 - val_accuracy: 0.5500
Epoch 4/10
7/7 [==============================] - 7s 1s/step - loss: 0.6790 - accuracy: 0.6116 - val_loss: 0.6765 - val_accuracy: 0.9500
Epoch 5/10
7/7 [==============================] - 8s 1s/step - loss: 0.6760 - accuracy: 0.7098 - val_loss: 0.6709 - val_accuracy: 0.9500
Epoch 6/10
7/7 [==============================] - 7s 1s/step - loss: 0.6677 - accuracy: 0.8929 - val_loss: 0.6626 - val_accuracy: 0.6000
Epoch 7/10
7/7 [==============================] - 8s 1s/step - loss: 0.6622 - accuracy: 0.7812 - val_loss: 0.6518 - val_accuracy: 0.7667
Epoch 8/10
7/7 [========================

In [28]:
model.evaluate(test_set)

2/2 [==============================] - 2s 956ms/step - loss: 0.6066 - accuracy: 0.5167


[0.6066101789474487, 0.5166666507720947]

In [29]:
from google.colab import drive
drive.mount('/content/drive')
from keras.models import save_model
model.save('/content/drive/MyDrive/SavedModels/AlexNet_Covid19_binary2.h5')

Mounted at /content/drive


In [30]:
y_pred=(model.predict(test_set)>=0.5).astype(int)
y_pred[:5]

2/2 [==============================] - 2s 691ms/step


array([[1],
       [1],
       [0],
       [1],
       [1]])

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(test_set.labels,y_pred))
print(accuracy_score(test_set.labels,y_pred)*100)

[[ 1 29]
 [ 0 30]]
51.66666666666667


In [32]:
# from keras.preprocessing import image
# img1 =tf.keras.utils.load_img('/content/CovidDataset/Val/Normal/NORMAL2-IM-0730-0001.jpeg' )
# img1.size

In [33]:
from keras.preprocessing import image
img1=image.image_utils.load_img('/content/CovidDataset/Val/Covid/41591_2020_819_Fig1_HTML.webp-day10.png',target_size=(224,224))
img1.size

(224, 224)

In [34]:
img =tf.keras.preprocessing.image.img_to_array(img1)
img.shape

(224, 224, 3)

In [35]:
import numpy as np
img = img/255
img_expand =np.expand_dims(img, axis =0)
img_expand.shape

(1, 224, 224, 3)

In [36]:
y_pred_img = model.predict(img_expand)
print(y_pred_img)

1/1 [==============================] - 0s 243ms/step
[[0.5519319]]


In [37]:
if y_pred_img >= 0.5:
    prediction = 'normal'
else:
    prediction = 'covid'
print(prediction)

normal


# references

data

https://drive.google.com/drive/folders/1c2dryLu9ME3eLgWh7m3NDdVde6jO2nOV?usp=share_link